# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Standard pre-commit checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']
        exclude: ".*\\.ipynb$"

  # Ruff — replaces black, isort, and flake8
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: ["--fix"]

  # Custom local hook for clearing notebook cell numbers
  - repo: local
    hooks:
      - id: clear-execution-counts
        name: Clear execution counts in notebooks
        entry: python clear_cell_nums.py
        language: system
        files: \.ipynb$
